version: '3.7'

services:
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment: 
      - SECRET_KEY=hoge
      - DATABASE_ENGINE=django.db.backends.postgresql
      - DATABASE_DB=django_db
      - DATABASE_USER=django_db_user
      - DATABASE_PASSWORD=password1234
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - postgres

  postgres:
    image: postgres:11.4-alpine
    volumes:
        - postgres_data:/var/lib/postgresql/data
    environment:
        - POSTGRES_USER=django_db_user
        - POSTGRES_PASSWORD=password1234
        - POSTGRES_DB=django_db

volumes:
  postgres_data: